# SPDX-FileCopyrightText: 2023 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

ifeq ($(PRODUCT_VIRTUAL_AB_OTA),true)
BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE ?= true
endif

ifeq (,$(filter true, $(WITHOUT_RESERVED_SIZE) $(WITH_GMS)))
BOARD_PRODUCTIMAGE_EXTFS_INODE_COUNT ?= -1

ifeq ($(BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE),true)
ifeq ($(PRODUCT_IS_ATV),true)
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 450000000
else # PRODUCT_IS_ATV
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 838036608
endif # PRODUCT_IS_ATV
else # BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE
ifeq ($(PRODUCT_IS_ATV),true)
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 470000000
else # PRODUCT_IS_ATV
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE ?= 1957691392
endif # PRODUCT_IS_ATV
endif # BOARD_PRODUCTIMAGE_MINIMAL_PARTITION_RESERVED_SIZE

BOARD_SYSTEMIMAGE_EXTFS_INODE_COUNT ?= -1
ifeq ($(PRODUCT_IS_ATV),true)
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE ?= 40000000
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE ?= 27000000
else # PRODUCT_IS_ATV
BOARD_SYSTEM_EXTIMAGE_EXTFS_INODE_COUNT ?= -1
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE ?= 94371840
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE ?= 94371840
endif # PRODUCT_IS_ATV

ifneq (,$(filter $(PRODUCT_DEVICE),m5_tab odroidc4_tab))
BOARD_PRODUCTIMAGE_PARTITION_RESERVED_SIZE := 150000000
BOARD_SYSTEMIMAGE_PARTITION_RESERVED_SIZE := 150000000
BOARD_SYSTEM_EXTIMAGE_PARTITION_RESERVED_SIZE := 100000000
endif # PRODUCT_DEVICE

endif # WITH_GMS
